-- Seeds 20 sample jobs. Requires at least one existing auth user
-- (jobs.poster_id references auth.users(id)).

with poster_pool as (
  select
    id,
    row_number() over (order by created_at) as rn
  from auth.users
),
pool_size as (
  select count(*) as size from poster_pool
),
seed_jobs as (
  select * from (
    values
      (1,
       'Senior Frontend Engineer',
       'Skyline Labs',
       'Remote (US)',
       'Full-Time',
       'published',
       'Build modern analytics experiences for product-led teams.',
       'We are looking for a senior frontend engineer to own customer-facing surfaces and push our design system forward.',
       ARRAY['Own core dashboard features with React and Next.js','Collaborate with design to ship polished UX improvements','Champion performance and accessibility across the app'],
       ARRAY['6+ years building React/TypeScript applications','Expertise with component architecture and design systems','Comfortable profiling and optimizing complex UI flows'],
       ARRAY['Competitive salary and equity','Remote-first culture with quarterly onsites','Comprehensive medical, dental, vision'],
       'Skyline Labs builds analytics products for high-growth SaaS teams and values craftsmanship, curiosity, and bias for action.',
       'https://jobs.skylinelabs.com/frontend',
       'hire@skylinelabs.com',
       timezone('utc', now()) - interval '3 days',
       140000,
       180000,
       'USD',
       ARRAY['React','TypeScript','SaaS']),
      (2,
       'Product Design Lead',
       'Northwind Collective',
       'Austin, TX',
       'Full-Time',
       'published',
       'Lead design vision for cross-platform operations tools.',
       'Help guide product discovery and execution for logistics experience teams.',
       ARRAY['Shape end-to-end journeys with research-backed insights','Run critiques and partner reviews to uphold visual quality','Mentor designers and partner with engineering for delivery'],
       ARRAY['8+ years in product design roles','Portfolio demonstrating shipped complex systems','Strong facilitation and stakeholder management skills'],
       ARRAY['Hybrid schedule with studio collaboration','Annual learning stipend','Comprehensive health coverage'],
       'Northwind Collective builds connected operations software and values craft, iteration, and clear communication.',
       'https://northwindcollective.com/careers/design-lead',
       'talent@northwindcollective.com',
       timezone('utc', now()) - interval '5 days',
       155000,
       195000,
       'USD',
       ARRAY['Design','UX','Leadership']),
      (3,
       'Platform Reliability Engineer',
       'TrussWorks',
       'Berlin, Germany',
       'Contract',
       'published',
       'Strengthen platform reliability and deployment pipelines.',
       'Partner with product squads to harden infrastructure, boost observability, and automate release workflows.',
       ARRAY['Improve CI/CD health and deployment throughput','Expand logging and tracing coverage for critical services','Coordinate incident reviews and resilience improvements'],
       ARRAY['5+ years across SRE, DevOps, or platform teams','Deep AWS and Kubernetes experience','Comfortable with Terraform and observability stacks'],
       ARRAY['6 month contract with possible extension','Co-working stipend plus remote budget','Quarterly travel for team planning'],
       'TrussWorks powers commerce infrastructure for modern consumer brands and invests in reliable experiences.',
       'https://truss.works/careers/platform-reliability',
       'people@truss.works',
       timezone('utc', now()) - interval '11 days',
       95000,
       120000,
       'EUR',
       ARRAY['DevOps','Kubernetes','AWS']),
      (4,
       'Customer Success Strategist',
       'FlowState',
       'Chicago, IL',
       'Full-Time',
       'published',
       'Partner with growth-stage customers to drive adoption and retention.',
       'Own onboarding, success planning, and expansion conversations across a portfolio of collaborative workspaces.',
       ARRAY['Develop success plans tied to customer outcomes','Lead executive business reviews and enablement sessions','Surface product feedback loops with product and engineering'],
       ARRAY['4+ years in B2B SaaS success or account roles','Strong facilitation and storytelling skills','Comfort working with leadership stakeholders'],
       ARRAY['Hybrid schedule with twice-monthly in-person collaboration','Professional development stipend','401(k) with company match'],
       'FlowState helps distributed product teams stay aligned with a calm, outcome-focused collaboration platform.',
       'https://flowstateapp.com/careers/csm',
       'careers@flowstateapp.com',
       timezone('utc', now()) - interval '7 days',
       85000,
       105000,
       'USD',
       ARRAY['Customer Success','B2B SaaS','Enablement']),
      (5,
       'Lifecycle Marketing Manager',
       'Beacon Media',
       'Remote (Canada)',
       'Full-Time',
       'draft',
       'Own lifecycle campaigns across email and in-product surfaces.',
       'Design segmented programs that nurture prospects and deepen customer engagement.',
       ARRAY['Design lifecycle campaigns that progress leads','Collaborate with creative on copy and assets','Analyze retention metrics to forecast impact'],
       ARRAY['5+ years lifecycle marketing experience','Comfortable with marketing automation platforms','Strong experimentation and segmentation skills'],
       ARRAY['Remote-first team across Canada','Monthly wellness stipend','Professional development budget'],
       'Beacon Media partners with creative brands on measurable marketing programs.',
       'https://beaconmedia.com/careers/lifecycle-manager',
       'jobs@beaconmedia.com',
       null::timestamptz,
       90000,
       110000,
       'CAD',
       ARRAY['Lifecycle','Email','Retention']),
      (6,
       'Data Visualization Developer',
       'Atlas Insights',
       'New York, NY',
       'Contract',
       'published',
       'Create interactive data stories for enterprise analytics clients.',
       'Collaborate with strategists to translate research into compelling visual narratives.',
       ARRAY['Build interactive dashboards with D3.js and Vega','Prototype data stories in collaboration with consultants','Optimize rendering performance across devices'],
       ARRAY['Expert with modern JavaScript data viz libraries','Comfortable working with complex datasets','Strong communication with non-technical stakeholders'],
       ARRAY['3 month contract with renewal options','Onsite kickoff followed by hybrid schedule','Access to data science mentors and tooling'],
       'Atlas Insights helps enterprises make smarter decisions with research-backed analytics products.',
       'https://atlasinsights.co/careers/data-viz-developer',
       'work@atlasinsights.co',
       timezone('utc', now()) - interval '1 day',
       70000,
       90000,
       'USD',
       ARRAY['D3.js','DataViz','Consulting']),
      (7,
       'Mobile Product Designer',
       'Lumi Labs',
       'Seattle, WA',
       'Full-Time',
       'published',
       'Design native mobile experiences for productivity tools.',
       'Define pattern libraries, conduct hands-on discovery, and ship polished mobile interfaces.',
       ARRAY['Design flows across iOS and Android apps','Run evaluative testing to validate iterations','Partner with engineering to ensure polish and accessibility'],
       ARRAY['5+ years designing mobile products','Strong visual craft and prototyping chops','Experience running user research independently'],
       ARRAY['Competitive salary and equity grants','Monthly commuter stipend','Robust parental leave'],
       'Lumi Labs builds productivity apps that help hybrid teams plan and prioritize with confidence.',
       'https://lumilabs.com/careers/mobile-designer',
       'design@lumilabs.com',
       timezone('utc', now()) - interval '4 days',
       130000,
       160000,
       'USD',
       ARRAY['Mobile','Product Design','Research']),
      (8,
       'DevOps Automation Specialist',
       'Nimble Systems',
       'Remote (EMEA)',
       'Contract',
       'published',
       'Automate infrastructure workflows for data-heavy SaaS platforms.',
       'Work with platform engineering to improve environment provisioning, security posture, and release automation.',
       ARRAY['Extend infrastructure as code coverage with Terraform','Improve CI pipelines and deployment orchestrations','Audit environments for security and compliance gaps'],
       ARRAY['Deep experience with Terraform and CI/CD tooling','Comfortable scripting in Python or Go','Knowledge of SOC2 and ISO27001 practices'],
       ARRAY['Remote friendly across EMEA time zones','6 month renewable contract','Professional certification support'],
       'Nimble Systems provides compliance-focused infrastructure for AI companies shipping quickly and safely.',
       'https://nimblesystems.dev/careers/devops-automation',
       'people@nimblesystems.dev',
       timezone('utc', now()) - interval '9 days',
       80000,
       95000,
       'EUR',
       ARRAY['Terraform','CI/CD','Automation']),
      (9,
       'Growth Marketing Analyst',
       'Brightside Apps',
       'Los Angeles, CA',
       'Full-Time',
       'draft',
       'Uncover insights that fuel paid growth experiments.',
       'Help the growth squad design, analyze, and scale performance marketing programs.',
       ARRAY['Analyze performance data to spot optimization wins','Partner with creative to test new messaging and offers','Build dashboards that highlight cohort trends'],
       ARRAY['3+ years in growth or performance analytics','Strong SQL and experimentation fundamentals','Experience managing reporting across paid channels'],
       ARRAY['Hybrid work with beachside coworking days','Health, dental, and vision benefits','Annual learning stipend'],
       'Brightside Apps creates mindful productivity tools and focuses on balanced, sustainable growth.',
       'https://brightsideapps.com/careers/growth-analyst',
       'jobs@brightsideapps.com',
       null::timestamptz,
       85000,
       95000,
       'USD',
       ARRAY['Growth','Analytics','Paid Media']),
      (10,
       'Technical Program Manager',
       'Vertex Robotics',
       'Toronto, Canada',
       'Full-Time',
       'published',
       'Drive cross-functional delivery for robotics integrations.',
       'Coordinate hardware and software teams to land complex enterprise deployments.',
       ARRAY['Own program plans spanning firmware, software, and ops','Run risk reviews and executive status updates','Improve delivery rituals and tooling across squads'],
       ARRAY['7+ years as TPM or engineering program lead','Experience shipping hardware plus cloud software','Excellent verbal and written communication'],
       ARRAY['Hybrid setup with lab access','RRSP matching and wellness stipend','Generous parental leave'],
       'Vertex Robotics builds autonomous systems that accelerate warehouse throughput for retail brands.',
       'https://vertexrobotics.ai/careers/tpm',
       'talent@vertexrobotics.ai',
       timezone('utc', now()) - interval '6 days',
       135000,
       160000,
       'CAD',
       ARRAY['Robotics','Program Management','Hardware']),
      (11,
       'UX Research Lead',
       'Gatherly',
       'Remote (EU)',
       'Full-Time',
       'published',
       'Shape research strategy across discovery and evaluative studies.',
       'Lead a small team of researchers uncovering insights for collaboration products.',
       ARRAY['Build research roadmaps with product and design','Conduct mixed-method studies across the product lifecycle','Coach partners on evidence-based decision making'],
       ARRAY['8+ years in UX research with team leadership','Fluency in both qualitative and quantitative methods','Strong storytelling and influence skills'],
       ARRAY['Remote across EU with quarterly retreats','Flexible working hours','Learning and conference budget'],
       'Gatherly helps hybrid teams run meetings that foster clarity and connection.',
       'https://gatherlyhq.com/careers/ux-research-lead',
       'people@gatherlyhq.com',
       timezone('utc', now()) - interval '8 days',
       115000,
       140000,
       'EUR',
       ARRAY['Research','Product Discovery','SaaS']),
      (12,
       'Site Reliability Engineer Contractor',
       'Atlas Commerce',
       'Austin, TX',
       'Contract',
       'published',
       'Maintain uptime for mission critical checkout APIs.',
       'Partner with backend squads to improve reliability, alerting, and game-day readiness.',
       ARRAY['Audit and tune alerting and runbooks','Lead incident reviews and resilience projects','Design guardrails for high risk deployments'],
       ARRAY['5+ years in SRE roles','Deep experience with Kubernetes and service meshes','Comfortable coding automation in Go or Python'],
       ARRAY['3 month engagement with possible extension','Onsite onboarding week then hybrid','Access to reliability tooling budget'],
       'Atlas Commerce powers digital storefront experiences for mid-market retailers with reliability as a core value.',
       'https://atlascommerce.com/careers/sre-contractor',
       'sre@atlascommerce.com',
       timezone('utc', now()) - interval '14 days',
       90000,
       115000,
       'USD',
       ARRAY['SRE','Kubernetes','Observability']),
      (13,
       'Partnerships Account Executive',
       'Horizon Tools',
       'Denver, CO',
       'Full-Time',
       'published',
       'Grow strategic partnerships that expand product reach.',
       'Own the full sales cycle for partner-sourced opportunities and co-marketing programs.',
       ARRAY['Prospect and close new solution partners','Build joint value propositions with marketing','Forecast pipeline health and report to leadership'],
       ARRAY['5+ years in SaaS partnerships or channel sales','Track record of hitting quota','Strong negotiation and relationship skills'],
       ARRAY['Hybrid Denver hub with travel stipend','Uncapped commission structure','Equity grants and full benefits'],
       'Horizon Tools builds collaboration software for technical field teams working in real time.',
       'https://horizontools.com/careers/partnerships-ae',
       'careers@horizontools.com',
       timezone('utc', now()) - interval '10 days',
       95000,
       125000,
       'USD',
       ARRAY['Sales','Partnerships','Channel']),
      (14,
       'Principal Data Engineer',
       'SignalForge',
       'Boston, MA',
       'Full-Time',
       'published',
       'Architect data platforms powering AI-assisted analytics.',
       'Lead the build-out of streaming and batch pipelines that empower downstream analytics teams.',
       ARRAY['Design scalable data models and governance frameworks','Mentor engineers and guide technical direction','Collaborate with product on roadmap prioritization'],
       ARRAY['10+ years in data engineering','Expertise with Spark, dbt, and lakehouse architectures','Strong leadership and communication skills'],
       ARRAY['Competitive salary with sizable equity','Hybrid office with commuter support','Unlimited PTO with minimum time off policy'],
       'SignalForge delivers predictive analytics for manufacturing firms seeking operational efficiencies.',
       'https://signalforge.io/careers/principal-data-engineer',
       'talent@signalforge.io',
       timezone('utc', now()) - interval '12 days',
       180000,
       220000,
       'USD',
       ARRAY['Data Engineering','Spark','Leadership']),
      (15,
       'Content Marketing Producer',
       'Driftwood Studio',
       'Remote (US)',
       'Part-Time',
       'published',
       'Produce editorial content that highlights customer stories.',
       'Plan and execute multimedia storytelling that showcases product value.',
       ARRAY['Develop editorial calendars with product marketing','Produce customer spotlights and thought leadership pieces','Manage freelancers for design and video assets'],
       ARRAY['4+ years in content marketing or journalism','Strong writing portfolio with B2B stories','Comfortable coordinating multimedia projects'],
       ARRAY['Part-time schedule ~20 hrs/week','Home office stipend','Access to creative tooling and workshops'],
       'Driftwood Studio crafts narrative-driven content for creative software teams.',
       'https://driftwoodstudio.co/careers/content-producer',
       'editorial@driftwoodstudio.co',
       timezone('utc', now()) - interval '2 days',
       60000,
       75000,
       'USD',
       ARRAY['Content','Storytelling','B2B']),
      (16,
       'Senior QA Automation Analyst',
       'Mercury Labs',
       'Chicago, IL',
       'Full-Time',
       'archived',
       'Own automated quality pipelines for financial compliance products.',
       'Drive automated coverage, regression stability, and release confidence.',
       ARRAY['Expand automated regression suites across services','Collaborate with engineers on shift-left testing','Report quality metrics and recommend improvements'],
       ARRAY['7+ years in QA automation','Expertise with Cypress or Playwright','Experience in regulated or fintech environments'],
       ARRAY['Health and dental coverage','401(k) with employer match','Annual certification stipend'],
       'Mercury Labs delivers compliance tooling for fintech teams and emphasizes reliability.',
       'https://mercurylabs.io/careers/qa-automation',
       'people@mercurylabs.io',
       timezone('utc', now()) - interval '210 days',
       105000,
       125000,
       'USD',
       ARRAY['QA','Automation','Fintech']),
      (17,
       'Solutions Architect Lead',
       'GridLayer',
       'London, UK',
       'Full-Time',
       'published',
       'Guide enterprise customers through complex architecture decisions.',
       'Partner with sales and delivery teams to blueprint scalable solutions.',
       ARRAY['Design reference architectures aligned to customer goals','Lead technical workshops and discovery','Support delivery teams during onboarding and rollout'],
       ARRAY['10+ years in solutions architecture or consulting','Deep knowledge of cloud platforms and integration patterns','Strong stakeholder management skills'],
       ARRAY['Hybrid London office with flexible Fridays','Pension contribution and private healthcare','Annual conference allowance'],
       'GridLayer provides integration tooling for regulated industries needing dependable data flows.',
       'https://gridlayer.com/careers/solutions-architect-lead',
       'talent@gridlayer.com',
       timezone('utc', now()) - interval '15 days',
       95000,
       120000,
       'GBP',
       ARRAY['Architecture','Cloud','Enterprise']),
      (18,
       'Product Marketing Strategist',
       'Arcadia AI',
       'San Francisco, CA',
       'Full-Time',
       'published',
       'Craft positioning and go-to-market programs for AI-driven workflows.',
       'Own storytelling, launch readiness, and competitive differentiation for new features.',
       ARRAY['Develop messaging frameworks with product and sales','Plan integrated launches with growth and comms','Enable revenue teams with assets and insights'],
       ARRAY['6+ years in product marketing','Experience launching AI or workflow products','Strong analytical and storytelling abilities'],
       ARRAY['Hybrid HQ with creative studio access','Equity plus comprehensive benefits','Generous wellness stipend'],
       'Arcadia AI builds collaborative automation tools that help teams focus on high-value work.',
       'https://arcadia.ai/careers/product-marketing-strategist',
       'pm@arcadia.ai',
       timezone('utc', now()) - interval '3 days',
       145000,
       175000,
       'USD',
       ARRAY['Product Marketing','AI','GTM']),
      (19,
       'Backend API Engineer',
       'RelayStack',
       'Remote (LATAM)',
       'Full-Time',
       'published',
       'Build resilient APIs that power integrations for logistics providers.',
       'Design, implement, and scale services that process millions of events daily.',
       ARRAY['Design and ship well-tested Node.js services','Collaborate with platform teams on observability','Improve reliability of partner integrations'],
       ARRAY['5+ years building backend systems','Expertise with Node.js or Go','Comfortable with message queues and event-driven architecture'],
       ARRAY['Remote-first across Latin America','Company-provided workspace stipend','Quarterly virtual summits'],
       'RelayStack connects logistics providers with retailers through a modern API-first platform.',
       'https://relaystack.io/careers/backend-api-engineer',
       'engineering@relaystack.io',
       timezone('utc', now()) - interval '4 days',
       110000,
       135000,
       'USD',
       ARRAY['Node.js','APIs','Logistics']),
      (20,
       'Head of Community Experience',
       'OpenLoop',
       'Portland, OR',
       'Full-Time',
       'archived',
       'Lead community programs that support product adopters and champions.',
       'Design strategic community initiatives, events, and content that drive adoption.',
       ARRAY['Define community programming and success metrics','Partner with product on feedback loops','Manage moderators and engagement channels'],
       ARRAY['8+ years building or leading community programs','Strong communication and facilitation skills','Experience working with SaaS customer communities'],
       ARRAY['Hybrid office with travel to customer hubs','Full benefits plus wellness stipend','Annual retreat with user community'],
       'OpenLoop helps product teams co-create with their users through data-informed community platforms.',
       'https://openloop.io/careers/head-of-community',
       'community@openloop.io',
       timezone('utc', now()) - interval '320 days',
       125000,
       150000,
       'USD',
       ARRAY['Community','Engagement','Customer Advocacy'])
  ) as t(
    seq,
    title,
    company_name,
    location,
    job_type_text,
    job_status_text,
    overview,
    description,
    responsibilities,
    requirements,
    benefits,
    about_company,
    application_url,
    application_email,
    published_at,
    salary_min,
    salary_max,
    salary_currency,
    tags
  )
)
insert into public.jobs (
  poster_id,
  title,
  company_name,
  location,
  job_type,
  job_status,
  overview,
  description,
  responsibilities,
  requirements,
  benefits,
  about_company,
  application_url,
  application_email,
  published_at,
  salary_min,
  salary_max,
  salary_currency,
  tags
)
select
  (select id
   from poster_pool
   where rn = ((seed.seq - 1) % pool_size.size) + 1),
  seed.title,
  seed.company_name,
  seed.location,
  seed.job_type_text::job_type,
  seed.job_status_text::job_status,
  seed.overview,
  seed.description,
  seed.responsibilities,
  seed.requirements,
  seed.benefits,
  seed.about_company,
  seed.application_url,
  seed.application_email,
  seed.published_at,
  seed.salary_min,
  seed.salary_max,
  seed.salary_currency,
  seed.tags
from seed_jobs seed
cross join pool_size
where pool_size.size > 0;
